baseURL: ""
languageCode: en-us
title: Bitlevi
theme: hugo-bearcub

params:
  homeInfoParams:
    Title: 'Welcome!'

menu:
  main:
    - identifier: posts
      name: Posts
      url: /posts
      weight: 1
    - identifier: guides
      name: Guides
      url: /guides
      weight: 2
    - identifier: about
      name: About
      url: /about
      weight: 3